
<img src="images/ruler.jpg"><br>
		
<p class="footer1">
Last Major Update: January 13, 2004
</p>

<br clear="all">
<table align="center" width="600">
<tr><td class="topicbar">Copyright Disclaimers</td></tr>
<tr>
<td><p class="footer">Star Trek, Star Trek: The Next Generation, Star Trek: Deep Space 9, Star Trek: Voyager and Star Trek Enterprise are registered trademarks of Paramount Pictures, Viacom and their respective owners.  No revenues are generated by the use of the Star Trek trademark and no copyright violation is intended.</p>
<p class="footer">This role-playing game and associated websites are purely for entertainment purposes. Some images used on this site courtesy of DevilsWorld6 and/or Collective 359.</p>
<p class="footer">This site is operated by Task Force Management System Copyright 2000-2004 SPMSDev Team. Originally created as a joint project of Ed Smith, Ben Lindstrom and Jason McCormick.</p>
<p class="footer"><a href="http://www.rpg-insignias.co.uk/" target="_New"><img src="images/rpginsigniassm.jpg" border="0" width="100" height="35" align="left" hspace="5"></a><font color="#7898AD" face="Arial">NOTICE:</font> The rank insignias on this site where created by <a href="mailto:smarriott@rpg-insignias.co.uk?subject=RPG Insignias">Steven Marriott</a>, originally for the <a href="http://www.tangofleet.org" target="_New">Tango Fleet PBE-RPG</a>. Please do not copy the images. If you wish to obtain them and an up-to-date copy either access the <a href="http://www.tangofleet.org" target="_New">Tango Fleet Website</a>, or visit the <a href="http://www.rpg-insignias.co.uk" target="_New">RPG-Insignias Website</a>.</font></p></td></tr>
</table>	
</center>